- .github/workflows/validate.yml
Creates a validate workflow that runs on every push and PR.
It will fail if the yaml file is misformatted.
> Create a validate workflow

- plugins.yaml
Apologies if anything is broken <3
> Include all Adde mods!

- plugins.yaml
Honestly if anything is broken with this just whack me with a big stick.
> Update Adde links

- plugins.yaml
> Add Portraits for News in Endless Sky

- plugins.yaml
Removing experimental dumping grounds from plugin lists meant for gameplay, as those are not intended for gameplay..
> Update Adde listings

- plugins.yaml
Adding my ship variants plugin to the list.
> Add Bardagh's ship variants

- plugins.yaml
Adds the Colorful Void Sprites mod to this collection
> Add Colorful Void Sprites

- manifests/Easier Korath Automatons.yaml
Added my plugin Easier Korath Automatons, which makes capping Sestor & Mereti easier by lowering self-destruct chances.
> Added Easier Korath Automatons

- manifests/ES News Portraits
- manifests/ES News Portraits.yaml
Adds ES-news-portraits to the plugin list.
> Add ES News Portraits

- manifests/The Adamas Project.yaml
> Added the Adamas Project

- manifests/The Adamas Project.yaml
Becuase toilethinges abandoned the Adamas Project, and I have taken the reins, I'm changing the source to my fork as it will be updated regularly(ish).
> Changing Adamas-Project to an updated fork

- manifests/Exporianes.yaml
Added my plugin Exporianes, since I finally finished my month of work on it.
Will be updating frequently, hope I got that code right.
> Adding Exporianes

- manifests/Exporianes.yaml
Updated Exporianes to v1.2 that I released yesterday.
Is the auto-update working?
I would normally think it would go to the new version after I made a new release, but the new release has been out for a while.
> Update Exporianes to v1.2

- manifests/Exporianes.yaml
> Update Exporianes to v1.3

- manifests/Exporianes.yaml
> Updated Exporianes to v1.4

- manifests/Lemuria's Extra ES Stuff.yaml
I am new to this, please help with the Auto Update section. Thanks
> Create Lemuria's Extra ES Stuff.yaml

- manifests/Endless Cargo.yaml
I guess ES Mod Share is kaput, and my mods need some modernizing anyway, so here's one of 'em.  Not sure if I did this right.
> Add Endless Cargo v0.2.0

- manifests/Quaernan Start.yaml
Read about the [plugin lore][lore].
Adds a new starting ship (Tier 3 civilization) which comes with deployable escorts.
Zoura please review (discord user `Zoura the Quaernan Guy` a.k.a. GitHub user @AvianGeneticist)
[lore]: https://discord.com/channels/251118043411775489/431496424992014347/950868719016476712
> Add Quaernan Start plugin

- manifests/Better Vanilla Pirates.yaml
> Better Vanilla Pirates

- manifests/Mega Freight.yaml
Made with https://raw.githack.com/quyykk/endless-sky.github.io/various-improvements/plugin-manifest-gen.html
> Upload Mega Freight

- manifests/Quaernan Start.yaml
I transferred the project to Zoura.
> Hosting transferred for Quaernan Start plugin

- manifests/spacecrate.yaml
> Add SpaceCrate.yaml

- manifests/a-conscience-plugin.yaml
Thanks for maintaining this repo.
> Update to v0.2.0 and update description.

- manifests/Mega Freight.yaml
(Hopefully I'm doing it the right way and not breaking anything.)
> Update MegaFreight description

- manifests/Blended Ships.yaml
Here's my plugin. Hopefully this is formatted right, I'll be happy to fix it if it isn't.
> Add Blended Ships

- manifests/Fire Corporation.yaml
This is my pull request for a fairly incomplete plugin. I hope the links are all correct.
**Important Question:**
I used the outfit template found at https://github.com/endless-sky/endless-sky/wiki/CreatingOutfits. Do I have to add to my copyright.txt file saying something about that?
> Add manifest for Fire Corporation plugin

- manifests/Cromha Expansion.yaml
Pull Request to add my plugin.
> Create Cromha Expansion.yaml

- manifests/Cromha Expansion.yaml
> Update Cromha Expansion.yaml

- generated/plugins/Cromha Expansion.json
It's just to update my plugin shown description.
> Update Cromha Expansion.json

- generated/plugins/Cromha Expansion.json
Reverts endless-sky/endless-sky-plugins#1010
> Revert "Update Cromha Expansion.json"

- manifests/es-ruin-the-fun.yaml
This should now be my plugin's description.
> Updated Ruin The Fun description

- manifests/Main Plot Plus.yaml
> Create Main Plot Plus.yaml

- manifests/Main Plot Plus.yaml
> Fix main plot plus version regression

- manifests/Capitalis Major.yaml
- manifests/Korath Retribution.yaml
- manifests/Mil'taj Protectorate.yaml
- manifests/QOL-Outfits.yaml
I hope I did this right, still not fully used to github, it should contain a .yaml file for Mil'taj Protectorate, Capitalis Major, QOL Outfita and Korath Retribution
> My Four Plugins

- manifests/galactic.capital.investment.yaml
> plugin galactic.capital.investment

- manifests/Nuclear Missile Buff.yaml
Adds my plugin called Nuclear Missile Buff.
> Nuclear Missile Buff

- manifests/Quazar Conundrum.yaml
Submitting this manifest for review and hopeful addition to the central plugin repository
> Create Quazar Conundrum.yaml

- generated/plugins/early-starts.json
- manifests/early-starts.yaml
Nothing exciting, just adding an icon so it gets picked up next sync.
> add iconUrl to early starts

- manifests/mission.helper.yml
> plugin mission.helper

- manifests/Bunsen.Burner.yml
- manifests/Factory.Outlets.yml
- manifests/Fundamental.Outfit.Expansion.yml
- manifests/Jaws.yml
- manifests/Korunak.Defense.Drones.yml
- manifests/Louise.Conglomerate.Shipyards.yml
- manifests/Solar.Sails.yml
- manifests/Zone.of.Control.yml
Once again. My fault. All requested changes are included.
> Add Lixi multi-repo plugins (repaired PR)
